options:
  command:
    name: df Command
    notes: The command used to display free disk space
    default: "df -h"
  filesystem:
    name: Filesystem
    notes: The filesystem to check usage, if none specified, uses the first listed
    default: 
      
metadata:
  used:          
    label: Disk Space Used
    units: GB
    precision: 0
  size:
    label: Disk Size
    units: GB
    precision: 0
  capacity:
    label: Disk Capacity
    units: %
    precision: 0
  avail:
    label: Disk Space Available
    units: GB
    precision: 0
    larger_is_better: true

triggers:
  - type: peak
    data_series_name: capacity
    max_value: 85
  # available disk space decreases by 10% compared to last week
  - type: trend
    data_series_name: avail
    direction: DOWN
    percentage_change: 10
    duration: 60
    window_reference: LAST_WEEK