options:
  user:
    name: MySQL username
    notes: Specify the username to connect with
    default: root
  password:
    name: MySQL password
    notes: Specify the password to connect with
  host:
    name: MySQL host
    notes: Specify something other than 'localhost' to connect via TCP
    default: localhost
  port:
    name: MySQL port
    notes: Specify the port to connect to MySQL with (if nonstandard)
  socket:
    name: MySQL socket
    notes: Specify the location of the MySQL socket

metadata:
  select:
    units: queries/sec
  delete:
    units: queries/sec
  update:
    units: queries/sec
  insert:
    units: queries/sec
  replace:
    units: queries/sec
  total:
    units: queries/sec

triggers:    
  - type: trend
    data_series_name: total
    direction: UP                            
    percentage_change: 30                    
    duration: 60                           
    window_reference: LAST_WEEK       